/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./components/card.vue')['default']
    Controls: typeof import('./components/controls.vue')['default']
    Description: typeof import('./components/description.vue')['default']
    Footer: typeof import('./components/footer.vue')['default']
    LocationSearch: typeof import('./components/location-search.vue')['default']
    Map: typeof import('./components/map.vue')['default']
    Marker: typeof import('./components/marker.vue')['default']
    NavigationHeader: typeof import('./components/navigation-header.vue')['default']
    Observations: typeof import('./components/observations.vue')['default']
    Popup: typeof import('./components/popup.vue')['default']
    ReturnBtn: typeof import('./components/return-btn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwellChart: typeof import('./components/swell-chart.vue')['default']
    Title: typeof import('./components/title.vue')['default']
  }
}
