/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./components/card.vue')['default']
    Controls: typeof import('./components/controls.vue')['default']
    Map: typeof import('./components/map.vue')['default']
    Marker: typeof import('./components/marker.vue')['default']
    Popup: typeof import('./components/popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title: typeof import('./components/title.vue')['default']
  }
}
